name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # O pipeline será executado em uma máquina virtual Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn

      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/hello-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-dockerhub-username/hello-app:${{ github.sha }}

      - name: Create Pull Request to update ArgoCD manifests
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Docker image tag"
          base: master  # A branch de destino para o Pull Request
          branch: update-image-tag  # Nome da branch do Pull Request
          title: "Update Docker image tag"
          body: "Automated update of Docker image tag in ArgoCD manifests"
